language: ruby
rvm:
  - 2.1.10
  - 2.2.8
  - 2.3.5
  - jruby-9.1.12.0

gemfile:
  - gemfiles/activesupport4.1.gemfile
  - gemfiles/activesupport4.2.gemfile
  - gemfiles/dalli2.gemfile

services:
  - redis
  - memcached
