language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.2
  - jruby-19mode

gemfile:
  - gemfiles/activesupport3.2.gemfile
  - gemfiles/activesupport4.0.gemfile
  - gemfiles/activesupport4.1.gemfile
  - gemfiles/dalli1.1.gemfile
  - gemfiles/dalli2.gemfile

services:
  - redis
  - memcached
