language: ruby
# Temporary workaround for minitest 4.7.5 installation error on ruby 2.1.0
before_install:
  - gem install bundler -v '>= 1.5.1'
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.1.1
  - jruby-19mode

gemfile:
  - gemfiles/activesupport3.2
  - gemfiles/activesupport4.0
  - gemfiles/dalli1.1
  - gemfiles/dalli2

services:
  - redis
  - memcached
