language: ruby
rvm:
  - 2.1.9
  - 2.2.5
  - 2.3.1
  - jruby-19mode

gemfile:
  - gemfiles/activesupport4.1.gemfile
  - gemfiles/activesupport4.2.gemfile
  - gemfiles/dalli2.gemfile

services:
  - redis
  - memcached
